### PR TITLE
Support middleman v5

### PR DESCRIPTION
**Pull request by le0pard**

### CODE REVIEW

**Comment by le0pard** [comment]
Should also close https://github.com/middleman/middleman-minify-html/issues/21

**Comment by tdreyno** [comment]
This is really great, thank you.

I am curious, what is the goal of using an options hash over the old `option` approach for the compress items? If possible, I'd love to avoid breaking API compatibility with v4 config files.

**Comment by le0pard** [comment]
@tdreyno thanks for feedback.

I moved its to separate config key, because thinking not to mix with additional options, like already added `ignore` and `content_types` (and maybe some future general options). 

I can back all configuration on one level, it is not an issue (maybe just need little more logic to remove general settings from config before pass its to `HtmlCompressor`).

If you want move them on one level and it is that this options will be with `ignore`, `content_types`, I can do this. Just confirm, that this looks good for configuration :)

**Comment by tdreyno** [comment]
Confirmed. Lets go back to one level so this doesn't break existing configs. Then 👍

**Comment by le0pard** [comment]
Done. Please check @tdreyno

**Pull request merged**
